# Generated by Django 3.2.5 on 2021-07-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_why_choos_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='why_choos_us',
            name='img',
        ),
    ]
